### PR TITLE
Update docker images used for integration testing

### PR DESCRIPTION
**Pull request by kerkhofsd**
Xenit Docker images have been open sourced!
https://github.com/xenit-eu/docker-alfresco

This PR updates the images used for integration testing.

### CODE REVIEW

**Comment by kerkhofsd** [comment]
> Looks good to me.
> I assume it builds ok.

**Comment by kerkhofsd** [comment]
@anghelutar apparently it doesn't build. Some timeout triggered while building on Travis.

**Comment by vierbergenlars** [comment]
You can split it up like roxana split up docker-solr: https://github.com/xenit-eu/docker-solr/pull/4/files

**Comment by kerkhofsd** [comment]
@vierbergenlars the timeout is already during the install phase, splitting up in parallel builds won't fix this?

**Comment by anghelutar** [comment]
But is it necessary to run ./gradlew assemble at all? (seems to take more than 30 min)
If not - you can simply disabling it with:

install:
  - true

**Comment by kerkhofsd** [comment]
@anghelutar that's the main Gradle task to actually build the project :slightly_smiling_face: ?

**Comment by anghelutar** [comment]
It runs anyway when it runs the command specified in script.

**Comment by anghelutar** [comment]
Otherwise it really needs that much time => higher time_wait needed.
Probably downloading new images.

**Comment by vierbergenlars** [comment]
> @vierbergenlars the timeout is already during the install phase, splitting up in parallel builds won't fix this?

Okay, I missed that part. Since some extra integration tests were added, I assumed they resulted in going over the timeout

**Pull request merged**
